package main

import (
	"strings"
	"testing"
)

func TestRenderGoreleaser(t *testing.T) {
	out := renderGoreleaser(Bundles)

	checks := []string{
		"# Code generated by probegen; DO NOT EDIT.",
		"binary: hc-core",
		`-tags, "hc_slim hc_http hc_https hc_tcp"`,
		"binary: hc-sql",
		`-tags, "hc_slim hc_tcp hc_postgres hc_mysql"`,
		`images: ["ghcr.io/moq77111113/hc-sql"]`,
		"cmd: cosign",
	}
	for _, c := range checks {
		if !strings.Contains(out, c) {
			t.Errorf("output missing %q", c)
		}
	}
}
