package main

import (
	"strings"
	"text/template"
)

// goreleaserTmpl renders the full .goreleaser.yaml. The full hc build and every
// fixed section are literal; per-bundle builds and images range over .Bundles.
// Delimiters are << >> so goreleaser's own {{ .Version }} passes through.
var goreleaserTmpl = template.Must(
	template.New("goreleaser").Delims("<<", ">>").Funcs(template.FuncMap{
		"slimTags": slimTags,
	}).Parse(`# Code generated by probegen; DO NOT EDIT.
version: 2

builds:
  - id: hc
    binary: hc
    main: .
    env: [CGO_ENABLED=0]
    flags: [-trimpath]
    ldflags: ["-s -w -X main.version={{ .Version }}"]
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos: [linux]
    goarch: [amd64, arm64]
<< range .Bundles >>
  - id: << .Binary >>
    binary: << .Binary >>
    main: .
    env: [CGO_ENABLED=0]
    flags: [-trimpath, -tags, "<< slimTags .Schemes >>"]
    ldflags: ["-s -w -X main.version={{ .Version }}"]
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos: [linux]
    goarch: [amd64, arm64]
<< end >>
# Raw binaries, not tarballs: hc is a single file you COPY into an image.
archives:
  - id: bins
    formats: [binary]
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt
  algorithm: sha256

sboms:
  - artifacts: binary

dockers_v2:
  - id: hc
    ids: [hc]
    dockerfile: Dockerfile.goreleaser
    images: ["ghcr.io/moq77111113/hc"]
    tags: ["{{ .Version }}", latest]
    platforms: [linux/amd64, linux/arm64]
    build_args: { BIN: hc }
    labels:
      org.opencontainers.image.source: https://github.com/Moq77111113/hc
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
<< range .Bundles >>
  - id: << .Binary >>
    ids: [<< .Binary >>]
    dockerfile: Dockerfile.goreleaser
    images: ["ghcr.io/moq77111113/<< .Binary >>"]
    tags: ["{{ .Version }}", latest]
    platforms: [linux/amd64, linux/arm64]
    build_args: { BIN: << .Binary >> }
    labels:
      org.opencontainers.image.source: https://github.com/Moq77111113/hc
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
<< end >>
# Keyless cosign, same GitHub OIDC identity for both surfaces, logged to Rekor.
signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--yes"
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "${artifact}"
    artifacts: checksum

docker_signs:
  - cmd: cosign
    artifacts: "" # dockers_v2 images
    args: ["sign", "--yes", "${artifact}@${digest}"]

release:
  prerelease: auto
`))

// renderGoreleaser executes goreleaserTmpl over the bundles. The template is a
// package-level constant, so an execution error is a programming bug — panic.
func renderGoreleaser(bundles []Bundle) string {
	var b strings.Builder
	if err := goreleaserTmpl.Execute(&b, map[string]any{"Bundles": bundles}); err != nil {
		panic(err)
	}
	return b.String()
}

// writeGoreleaser renders and writes the config to path.
func writeGoreleaser(path string) error {
	return writeGenerated(path, renderGoreleaser(Bundles))
}
