package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Moq77111113/hc/internal/probe"
)

// renderSlimTest builds the per-scheme slim registry test: in a build tagged
// for s alone, s (and its aliases) must be registered and no other scheme may.
func renderSlimTest(s probe.Scheme, all []probe.Scheme) string {
	var negTags, absent []string
	for _, o := range all {
		if o.Name == s.Name {
			continue
		}
		negTags = append(negTags, "!hc_"+o.Name)
		absent = append(absent, o.Name)
		absent = append(absent, o.Aliases...)
	}
	present := append([]string{s.Name}, s.Aliases...)

	tag := fmt.Sprintf("//go:build hc_slim && hc_%s", s.Name)
	if len(negTags) > 0 {
		tag += " && " + strings.Join(negTags, " && ")
	}

	var b strings.Builder
	fmt.Fprintln(&b, "// Code generated by probegen; DO NOT EDIT.")
	fmt.Fprintln(&b, tag)
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "package probe")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, `import "testing"`)
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "func TestSlimBuild_%s(t *testing.T) {\n", s.Name)
	fmt.Fprintf(&b, "\tpresent := %s\n", goStringSlice(present))
	fmt.Fprintf(&b, "\tabsent := %s\n", goStringSlice(absent))
	fmt.Fprintln(&b, "\tfor _, s := range present {")
	fmt.Fprintln(&b, "\t\tif _, ok := probers[s]; !ok {")
	fmt.Fprintf(&b, "\t\t\tt.Errorf(\"scheme %%q must be registered in slim %s build\", s)\n", s.Name)
	fmt.Fprintln(&b, "\t\t}")
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "\tfor _, s := range absent {")
	fmt.Fprintln(&b, "\t\tif _, ok := probers[s]; ok {")
	fmt.Fprintf(&b, "\t\t\tt.Errorf(\"scheme %%q must NOT be registered in slim %s build\", s)\n", s.Name)
	fmt.Fprintln(&b, "\t\t}")
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "}")
	return b.String()
}

// goStringSlice renders a []string literal: {"a", "b"}.
func goStringSlice(items []string) string {
	quoted := make([]string, len(items))
	for i, s := range items {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

// writeSlimTests removes stale hand-written slim tests and writes one generated
// file per scheme into dir.
func writeSlimTests(dir string) error {
	stale, err := filepath.Glob(filepath.Join(dir, "registry_*_slim_test.go"))
	if err != nil {
		return err
	}
	extra, err := filepath.Glob(filepath.Join(dir, "registry_slim_test.go"))
	if err != nil {
		return err
	}
	for _, f := range append(stale, extra...) {
		if err := os.Remove(f); err != nil {
			return err
		}
	}
	for _, s := range probe.Catalog {
		path := filepath.Join(dir, fmt.Sprintf("registry_%s_slim_gen_test.go", s.Name))
		if err := os.WriteFile(path, []byte(renderSlimTest(s, probe.Catalog)), 0o644); err != nil {
			return err
		}
	}
	return nil
}
