package main

import (
	"strings"
	"testing"

	"github.com/Moq77111113/hc/internal/probe"
)

func TestRenderSlimTest(t *testing.T) {
	out := renderSlimTest(probe.Postgres, probe.Catalog)

	checks := []string{
		"// Code generated by probegen; DO NOT EDIT.",
		"//go:build hc_slim && hc_postgres && !hc_http && !hc_https && !hc_tcp && !hc_mysql && !hc_redis",
		"package probe",
		`present := []string{"postgres", "pg"}`,
		`absent := []string{"http", "https", "tcp", "mysql", "redis"}`,
	}
	for _, c := range checks {
		if !strings.Contains(out, c) {
			t.Errorf("output missing %q\n---\n%s", c, out)
		}
	}
}
