// Code generated by probegen; DO NOT EDIT.
//go:build hc_slim && hc_redis && !hc_http && !hc_https && !hc_tcp && !hc_postgres && !hc_mysql

package probe

import "testing"

func TestSlimBuild_redis(t *testing.T) {
	present := []string{"redis"}
	absent := []string{"http", "https", "tcp", "postgres", "pg", "mysql"}
	for _, s := range present {
		if _, ok := probers[s]; !ok {
			t.Errorf("scheme %q must be registered in slim redis build", s)
		}
	}
	for _, s := range absent {
		if _, ok := probers[s]; ok {
			t.Errorf("scheme %q must NOT be registered in slim redis build", s)
		}
	}
}
