// Code generated by probegen; DO NOT EDIT.
//go:build hc_slim && hc_mysql && !hc_http && !hc_https && !hc_tcp && !hc_postgres && !hc_redis

package probe

import "testing"

func TestSlimBuild_mysql(t *testing.T) {
	present := []string{"mysql"}
	absent := []string{"http", "https", "tcp", "postgres", "pg", "redis"}
	for _, s := range present {
		if _, ok := probers[s]; !ok {
			t.Errorf("scheme %q must be registered in slim mysql build", s)
		}
	}
	for _, s := range absent {
		if _, ok := probers[s]; ok {
			t.Errorf("scheme %q must NOT be registered in slim mysql build", s)
		}
	}
}
